compile-time literals
emilk/snake_case pull request #5
Opened 2021-04-07 15:33 UTC by VladimirBramstedt

adding a macro to create compile-time validated `SnakeCaseRef<'static>`. feature flagged because requires rust 1.51 for const_generics.

2021-04-07 16:06 UTC, emilk requested changes
Thank you for this!

2021-04-07 16:06 UTC, emilk commented on src/lib.rs
> +macro_rules! scr_lit {
`scr_lit` is maybe a bit too cryptic. I think `snake_case!("yes_it_is")` would be better, no?

2021-04-07 16:06 UTC, emilk commented on src/lib.rs
> +/// this will construct a SnakeCafeRef with compile-time validation for string literals.
```suggestion
/// this will construct a SnakeCafeRef with compile-time validation for string literals.
///
/// ```
/// use snake_case::scr_lit;
/// let snake_case = scr_lit!("my_little_snake");
/// ```
```

2021-04-08 07:41 UTC, VladimirBramstedt commented on src/lib.rs
> +macro_rules! scr_lit {
yeah i think `snake_case!` is clearer, but im thinking it should be clear this doesnt actually produce a `SnakeCase` typ, but rather a `SnakeCaseRef`. a little naming conflict or something. maybe its just me though, and renaming it would be fine.

2021-04-08 07:43 UTC, VladimirBramstedt commented on src/lib.rs
> +/// this will construct a SnakeCafeRef with compile-time validation for string literals.
can also add the failing case behind a comment ` // let bad_snake = scr_lit!("Python"); <-wont compile`

2021-04-08 16:51 UTC, emilk approved these changes

2021-04-08 16:52 UTC, merged